---
- name: Update package list
  command: apt update

- name: Install necessary packages
  command: >
    apt install -y
    aptitude
    git
    mosh
    openssh-server
    python3
    python3-apt
    python3-pip

- name: Install required Python modules
  pip:
    name:
      - setuptools
      - wheel
      - pexpect

- name: Setup SSH directory
  file:
    path: /home/{{ ansible_user }}/.ssh
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700

- name: Allow SSH public key
  copy:
    src: "{{ ssh_public_key }}"
    dest: /home/{{ ansible_user }}/.ssh/authorized_keys
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0655

- name: Disable HDMI on boot
  lineinfile:
    path: /etc/rc.local
    backup: yes
    regex: "^exit 0$"
    insertbefore: "^exit 0"
    line: "/usr/bin/tvservice -o"
